-- SQL to create patients table matching components/patient-form.tsx
-- Use a conditional DO block to create the enum type to avoid syntax
-- errors on Postgres versions that don't support CREATE TYPE IF NOT EXISTS.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'severity_level') THEN
    CREATE TYPE public.severity_level AS ENUM ('mild','moderate','severe','critical');
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS public.patients (
  id bigint generated by default as identity primary key,
  full_name text not null,
  age integer,
  gender text,
  diagnosis text,
  severity public.severity_level default 'moderate' not null,
  expected_duration text,
  admission_date date,
  assigned_bed text,
  attending_doctor text,
  notes text,
  vitals jsonb,
  created_at timestamptz default now()
);

